### ISSUE TITLE
您好, 请问这个项目还在开发吗?

### ISSUE THREAD

**Issue by cxgreat2014** [nerososft/blog#1]
看到您的项目是github上唯一开源的restful blog, 我想自己下载下来试运行一番, 发现尽管我修改了数据库配置和其他的一些错误之后还是无法正常运行,请问该怎么运行起来呢?谢谢

**Comment by nerososft** [comment]
下载修改数据库，放在lamp环境下就可以啦

**Comment by nerososft** [comment]
好久不开发了

**Comment by cxgreat2014** [comment]
哈哈~谢谢回复，不过数据库字段是。。。？

**Comment by cxgreat2014** [comment]
一直没找到数据库在哪。。小白求助

**Comment by nerososft** [comment]
这个我估计找不到了，    不好意思， 想做博客的话看看这个https://github.com/nerososft/tutorial_tpblog，录了全程视频教程，可以给你

**Comment by nerososft** [comment]
数据库你要运行的，下载一个wamp或者xampp

**Comment by cxgreat2014** [comment]
好的，谢谢~
